apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gopherify

resources:
  - ../base
  - ingress.yaml
  - postgres/postgres-deployment.yaml
  - postgres/postgres-service.yaml
  - job-users-migrator.yaml

patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: users-deployment

secretGenerator:
  - name: users-db-secret
    namespace: gopherify
    literals:
      - DB_HOST=postgres.gopherify.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

generatorOptions:
  disableNameSuffixHash: true
