apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: users-backendpolicy
  namespace: gopherify
spec:
  targetRef:
    group: ""
    kind: Service
    name: users-service
  default:
    timeoutSec: 30
    connectionDraining:
      drainingTimeoutSec: 60
    sessionAffinity:
      type: NONE
    logging:
      enabled: true
      sampleRate: 1000000
