apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gopherify-gateway
  namespace: gateways-prod
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: backend-ip
  listeners:
    - name: https
      hostname: "api.users.gopherify.com"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        options:
          networking.gke.io/pre-shared-certs: gopherify-api-cert
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              domain: users
