apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gopherify-gateway
  namespace: gateways-prod
spec:
  gatewayClassName: gke-l7-global-external-managed
  addresses:
    - type: NamedAddress
      value: backend-ip
  listeners:
    - name: main
      port: 443
      protocol: HTTPS
      hostname: "*.gopherify.com"
      tls:
        mode: Terminate
        options:
          networking.gke.io/pre-shared-certs: mcrt-xxxx
      allowedRoutes:
        namespaces:
          from: All
