apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gopherify

resources:
  - ../base
  - gateway.yaml
  - httproute.yaml
  - backendpolicy.yaml
  - healthcheckpolicy.yaml

patches:
  - path: patches/namespace-patch.yaml
    target:
      kind: Namespace
      name: gopherify
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: users-deployment
