apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: users-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "backend-ip"
    networking.gke.io/managed-certificates: "gopherify-cert"
spec:
  ingressClassName: gce
  rules:
    - host: api.users.gopherify.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: users-service
                port:
                  number: 80
