apiVersion: v1
kind: Service
metadata:
  name: users-service
  annotations:
    beta.cloud.google.com/backend-config: '{"default":"users-backendconfig"}'
spec:
  type: ClusterIP
  selector:
    app: users
  ports:
    - port: 80
      targetPort: 3000
