apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: users
          image: europe-west4-docker.pkg.dev/devops-fmi-course-2025/devops-fmi-course-repo/backend-app
          ports:
            - name: http
              containerPort: 8080
            - name: grpc
              containerPort: 8079
          envFrom:
            - secretRef:
                name: users-db-secret
          env:
            - name: HTTP_PORT
              value: "8080"
            - name: GRPC_PORT
              value: "8079"
            - name: ALLOWED_ORIGINS
              value: "https://devops-chi-khaki.vercel.app"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          startupProbe:
            grpc:
              port: 8079
              service: "user.v1.UserService"
            failureThreshold: 15
            periodSeconds: 2
          livenessProbe:
            grpc:
              port: 8079
              service: "user.v1.UserService"
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 8079
              service: "user.v1.UserService"
            initialDelaySeconds: 5
            periodSeconds: 5
