apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: users-prod

resources:
  - ../../base/users
  - namespace.yaml
  - httproute.yaml
  - backendpolicy.yaml
  - healthcheckpolicy.yaml

patches:
  - path: patches/deployment-patch.yaml
    target:
      kind: Deployment
      name: users-deployment
