apiVersion: v1
kind: Namespace
metadata:
  name: users-dev
  labels:
    domain: users
    environment: dev

    # PSA: Least restrictive ENFORCE for development
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest

    # PSA: Warn developers when restricted rules would be violated
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest

    # PSA: Log violations of restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
