name: Backend CD

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - "k8s/**"
      - ".github/workflows/backend-cd.yaml"

permissions:
  id-token: write
  contents: read

env:
  GCP_PROJECT_ID: devops-fmi-course-476112
  GCP_ZONE: europe-west4-a
  GCP_CLUSTER: devops-fmi-course-gke
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/632982591699/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions
  GCP_SA_EMAIL: github-terraform-deployer@devops-fmi-course-476112.iam.gserviceaccount.com
  IMAGE_REPO: europe-west4-docker.pkg.dev/devops-fmi-course-476112/devops-fmi-course-repo/backend-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authenticate to GCP via OIDC
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SA_EMAIL }}
          token_format: "access_token"
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          install_components: gke-gcloud-auth-plugin

      - name: Enable GKE gcloud auth plugin
        run: echo "USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker europe-west4-docker.pkg.dev --quiet

      - name: Build and push backend Docker image
        run: |
          TAG="${GITHUB_SHA}"
          IMAGE="${IMAGE_REPO}:${TAG}"

          echo "Building image: $IMAGE"
          docker build -f ./backend/cmd/service/Dockerfile -t "$IMAGE" ./backend
          docker push "$IMAGE"

          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials "$GCP_CLUSTER" \
            --zone "$GCP_ZONE" \
            --project "$GCP_PROJECT_ID"

      - name: Install Kustomize
        uses: imranismail/setup-kustomize@v2.1.0
        with:
          kustomize-version: "*"

      - name: Deploy with Kustomize
        run: |
          cd k8s/prod
          kustomize edit add annotation app.git_commit:${GITHUB_SHA}
          kustomize edit add annotation kubernetes.io/change-cause:"Deployed via GitHub Actions commit ${GITHUB_SHA}"
          kustomize edit set image "${IMAGE_REPO}=${IMAGE_REPO}:${IMAGE_TAG}"
          kustomize build . | kubectl apply -f -
